version: '3.7'

services:
  nginx:
    image: nginx:1.19
    container_name: ci4_nginx
    volumes:
      - ./public:/var/www/ci/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_fpm
      - mysql
    ports:
      - "80:80"
      
  php_fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: always
    working_dir: /var/www/ci
    container_name: ci4_php_fpm
    volumes:
      - ./:/var/www/ci
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: ci4_mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./docker/mysql/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: codeigniter
      MYSQL_ROOT_PASSWORD: secret123!
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: secret

  redis:
    image: redis:6.0
    container_name: ci4_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    command: redis-server --appendonly yes

volumes:
  ci-4:
